name: dialog_spinner
description: A Flutter package to make dialog mode of spinner in android available in flutter
version: 0.1.2
author: Varun Dwivedi <eagleranger96@gmail.com>
homepage: https://github.com/eagleranger96/dialog_spinner

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
